title: "This is a Real Newssite"
description: "Satire, parody, and nonsense reporting."
url: "https://emiliabronk.github.io"
baseurl: "/news"
timezone: "America/New_York"
markdown: kramdown
theme: null
permalink: pretty
