title: "This is a Real Newssite"
description: "lol. you thought this was real?. i love you john oliver"
url: "https://emiliabronk.github.io"
baseurl: "/news"
timezone: "America/New_York"
markdown: kramdown
theme: null
permalink: pretty
